version: '3'

services:
  db:
    image: postgres:14.0
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    environment:
      - TZ=Asia/Almaty
      - POSTGRES_DB=djangogram
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=733362
    ports:
      - "5555:5432"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/code/static
      - media:/code/media
    command: bash -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - TZ=Asia/Almaty
      - DB_HOST=db
    restart: always

volumes:
  postgresql_data:
    external: true
  media:
    external: true
  static:
    external: true